[package]
name = "ainest_contract"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = "2.11.4"  # Use latest available
# No need for cairo_execute — we’re building a contract, not an executable

[dev-dependencies]
snforge_std = "0.45.0"
assert_macros = "2.11.4"

[[target.starknet-contract]]
sierra = true
casm = true

[tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]

[scripts]
test = "snforge test"
